return {
  'akinsho/bufferline.nvim',
  dependencies = {
    'moll/vim-bbye',
    'nvim-tree/nvim-web-devicons',
  },
  config = function()
    require('bufferline').setup {
      options = {
        mode = 'buffers', -- set to "tabs" to only show tabpages instead
        themable = true, -- allows highlight groups to be overriden i.e. sets highlights as default
        numbers = 'none', -- | "ordinal" | "buffer_id" | "both" | function({ ordinal, id, lower, raise }): string,
        close_command = 'Bdelete! %d', -- can be a string | function, see "Mouse actions"
        buffer_close_icon = '',
        close_icon = '',
        path_components = 1, -- Show only the file name without the directory
        modified_icon = '●',
        left_trunc_marker = '',
        right_trunc_marker = '',
        max_name_length = 30,
        max_prefix_length = 30, -- prefix used when a buffer is de-duplicated
        tab_size = 21,
        diagnostics = false,
        diagnostics_update_in_insert = false,
        color_icons = true,
        show_buffer_icons = true,
        show_buffer_close_icons = true,
        show_close_icon = true,
        persist_buffer_sort = true, -- whether or not custom sorted buffers should persist
        separator_style = { '│', '│' }, -- | "thick" | "thin" | { 'any', 'any' },
        enforce_regular_tabs = true,
        always_show_bufferline = true,
        show_tab_indicators = false,
        indicator = {
          -- icon = '▎', -- this should be omitted if indicator style is not 'icon'
          style = 'none', -- Options: 'icon', 'underline', 'none'
        },
        icon_pinned = '󰐃',
        minimum_padding = 1,
        maximum_padding = 5,
        maximum_length = 15,
        sort_by = 'insert_at_end',
      },
      highlights = {
        separator = {
          fg = '#434C5E',
        },
        buffer_selected = {
          bold = true,
          italic = false,
        },
        -- separator_selected = {},
        -- tab_selected = {},
        --background = {bg = '#000000'},
        -- indicator_selected = {},
        fill = {bg='#0e0e0e'},
        background = {bg='#0e0e0e'},
        tab = {bg='#0e0e0e'},
        tab_selected = {bg='#0e0e0e'},
        tab_separator = {bg='#0e0e0e'},
        tab_separator_selected = {bg='#0e0e0e'},
        tab_close = {bg='#0e0e0e'},
        close_button = {bg='#0e0e0e'},
        close_button_visible = {bg='#0e0e0e'},
        close_button_selected = {bg='#0e0e0e'},
        buffer_visible = {bg='#0e0e0e'},
        buffer_selected = {bg='#0e0e0e'},
        numbers = {bg='#0e0e0e'},
        numbers_visible = {bg='#0e0e0e'},
        numbers_selected = {bg='#0e0e0e'},
        diagnostic = {bg='#0e0e0e'},
        diagnostic_visible = {bg='#0e0e0e'},
        diagnostic_selected = {bg='#0e0e0e'},
        hint = {bg='#0e0e0e'},
        hint_visible = {bg='#0e0e0e'},
        hint_selected = {bg='#0e0e0e'},
        hint_diagnostic = {bg='#0e0e0e'},
        hint_diagnostic_visible = {bg='#0e0e0e'},
        hint_diagnostic_selected = {bg='#0e0e0e'},
        info = {bg='#0e0e0e'},
        info_visible = {bg='#0e0e0e'},
        info_selected = {bg='#0e0e0e'},
        info_diagnostic = {bg='#0e0e0e'},
        info_diagnostic_visible = {bg='#0e0e0e'},
        info_diagnostic_selected = {bg='#0e0e0e'},
        warning = {bg='#0e0e0e'},
        warning_visible = {bg='#0e0e0e'},
        warning_selected = {bg='#0e0e0e'},
        warning_diagnostic = {bg='#0e0e0e'},
        warning_diagnostic_visible = {bg='#0e0e0e'},
        warning_diagnostic_selected = {bg='#0e0e0e'},
        error = {bg='#0e0e0e'},
        error_visible = {bg='#0e0e0e'},
        error_selected = {bg='#0e0e0e'},
        error_diagnostic = {bg='#0e0e0e'},
        error_diagnostic_visible = {bg='#0e0e0e'},
        error_diagnostic_selected = {bg='#0e0e0e'},
        modified = {bg='#0e0e0e'},
        modified_visible = {bg='#0e0e0e'},
        modified_selected = {bg='#0e0e0e'},
        duplicate_selected = {bg='#0e0e0e'},
        duplicate_visible = {bg='#0e0e0e'},
        duplicate = {bg='#0e0e0e'},
        separator_selected = {bg='#0e0e0e'},
        separator_visible = {bg='#0e0e0e'},
        separator = {bg='#0e0e0e'},
        indicator_visible = {bg='#0e0e0e'},
        indicator_selected = {bg='#0e0e0e'},
        pick_selected = {bg='#0e0e0e'},
        pick_visible = {bg='#0e0e0e'},
        pick = {bg='#0e0e0e'},
        offset_separator = {bg='#0e0e0e'},
        trunc_marker = {bg='#0e0e0e'},
        },
    }
  end,
}
